### ISSUE TITLE
addWidget line not being rendered?

### ISSUE THREAD

**Issue by cjlee01** [MrWangJustToDo/git-diff-view#13]
Hi there,
i have an issue where the renderWidgetLine is not being rendered, is there specific things needed for it to render?
diffViewAddWidget is true and onAddWidgetClick is sending back a console.log when i click it ? Thanks in advance :)

**Comment by MrWangJustToDo** [comment]
try to install latest release , SEE https://github.com/MrWangJustToDo/git-diff-view/releases/tag/v0.0.20
