### ISSUE TITLE
Should Dark Mode be offered?

### ISSUE THREAD

**Issue by RickySharki** [MrWangJustToDo/git-diff-view#3]
The project runs in dark mode, but git-diff-view not dark mode
![image](https://github.com/user-attachments/assets/3dcf09c8-e1ff-40e5-9451-c43ebbd04072)

**Comment by congziqi77** [comment]
I also need dark mode, so does the author plan to add dark mode?

**Comment by MrWangJustToDo** [comment]
planning

**Comment by congziqi77** [comment]
@MrWangJustToDo Can I trouble the author to publish a release that includes the dark theme

**Comment by MrWangJustToDo** [comment]
already included in the latest release  [v0.0.17](https://github.com/MrWangJustToDo/git-diff-view/releases)
